// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY7J9D0BaCxptWu8B83SGN8jsCaFMObH0',
    appId: '1:702417938707:web:34825d6042c5ca7b4c12e6',
    messagingSenderId: '702417938707',
    projectId: 'medicall-mobile-app',
    authDomain: 'medicall-mobile-app.firebaseapp.com',
    databaseURL: 'https://medicall-mobile-app.firebaseio.com',
    storageBucket: 'medicall-mobile-app.appspot.com',
    measurementId: 'G-92PLWSB4CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7c-8Es-aZFEuF-aWYErgnfS0vNrM83hk',
    appId: '1:702417938707:android:5eec21360f2184284c12e6',
    messagingSenderId: '702417938707',
    projectId: 'medicall-mobile-app',
    databaseURL: 'https://medicall-mobile-app.firebaseio.com',
    storageBucket: 'medicall-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy934nS4HOo77MrUGG7zVWKhxKVz45u-k',
    appId: '1:702417938707:ios:1b4d56c0cbed6e554c12e6',
    messagingSenderId: '702417938707',
    projectId: 'medicall-mobile-app',
    databaseURL: 'https://medicall-mobile-app.firebaseio.com',
    storageBucket: 'medicall-mobile-app.appspot.com',
    iosBundleId: 'com.example.scanSunmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy934nS4HOo77MrUGG7zVWKhxKVz45u-k',
    appId: '1:702417938707:ios:1b4d56c0cbed6e554c12e6',
    messagingSenderId: '702417938707',
    projectId: 'medicall-mobile-app',
    databaseURL: 'https://medicall-mobile-app.firebaseio.com',
    storageBucket: 'medicall-mobile-app.appspot.com',
    iosBundleId: 'com.example.scanSunmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmcsJxzwysuHlz6VXBlVykvTWKmPgDQpI',
    appId: '1:702417938707:web:cb64188a908ad74e4c12e6',
    messagingSenderId: '702417938707',
    projectId: 'medicall-mobile-app',
    authDomain: 'medicall-mobile-app.firebaseapp.com',
    databaseURL: 'https://medicall-mobile-app.firebaseio.com',
    storageBucket: 'medicall-mobile-app.appspot.com',
    measurementId: 'G-WBX34NWV55',
  );
}
